name: Terraform-bastion

on:
  workflow_call:
    inputs:
      action:
        description: 
        required: true
        type: string
       

env:
  AWS_REGION: us-east-1
  EXPENSE_DIR: 30-bastion

jobs:
  terraform-bastion:
    name: Terraform-Bastion
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.EXPENSE_DIR }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@V3

    - name: set up AWS credentials
      uses: aws-actions/configure-aws-credentials@V3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    
    - name: Setup Terraform
      uses: terraform init -reconfigure

    - name: Terraform init
      run: hashicorp/setup-terraform@v2

    - name: Terraform Plan
      if: ${{ inputs.action == 'apply' }}
      run: terraform apply -auto-approve tfplan

    - name: Terraform Apply
      if: ${{ inputs.action == 'apply' }}
      run: terraform apply -auto-approve tfplan
    
    - name: Terraform Destroy
      if: ${{ inputs.action == 'destroy' }}
      run: terraform apply -auto-approve 